
objs-y += clock_win.o
objs-y += help_win.o
objs-y += statusline.o
objs-y += line_win.o
objs-y += window_center.o
objs-y += playlist_win.o
objs-y += config_win.o
objs-y += manager_win.o
objs-y += browse_win.o
objs-y += selectable_win.o

objs-$(CONFIG_TUI_MPD_VISUALIZER) += visual_win.o
objs-$(CONFIG_LIB_GLYR) += lyrics_win.o
objs-$(CONFIG_LIB_GLYR) += artist_win.o

