
#include <stdio.h>

#include "config.h"

void m_begin(void)
{
    printf("#\n"
           "# File generated by 'config'\n"
           "#\n"
           "# *** DO NOT EDIT THIS FILE DIRECTLY ***\n"
           "# ***     IT WILL BE OVERWRITTEN     ***\n"
           "#\n"
           "\n");
}

void m_end(void)
{

}

void m_write_var(enum output_type type, const char *prefix, const char *var,  const char *dat)
{
    switch (type) {
    case OUTPUT_YES:
        printf("CONFIG_%s%s := y\n", prefix? prefix: "", var);
        break;
    case OUTPUT_NO:
        printf("# CONFIG_%s%s := n\n", prefix? prefix: "", var);
        break;
    case OUTPUT_QUOTE_STRING:
        printf("CONFIG_%s%s := \"%s\"\n", prefix? prefix: "", var, dat);
        break;
    case OUTPUT_NOQUOTE_STRING:
        printf("CONFIG_%s%s := %s\n", prefix? prefix: "", var, dat);
        break;
    }
}

struct config_output m_output = {
    .start = m_begin,
    .end = m_end,
    .write_var = m_write_var,
};

